name: autobuild
on:
  push:
    branches:
      - main
  release:
    types:
      - published
jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run build
      - name: Deploy
        if: ${{ github.event_name == 'release' && github.event.action == 'published' }}        
        # https://github.com/JamesIves/github-pages-deploy-action
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: main
          folder: build
          token: ${{ secrets.GH_PAT }}
          repository-name: ryansheehan/ryansheehan.github.io
          clean-exclude: >
            .nojekyll
